name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:
  
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - name: Install requirements and run unitest
        run: |
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          pytest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      - name: Configure AWS credentials
        run: aws s3api list-buckets
          
